version: '3'

networks: 
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports: 
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker-components/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks: 
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php7.4
    volumes: 
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel